#
# APPLICATION CONFIG PROD
#

spring:
  ai:
    openai:
      api-key: <OPEN_AI_API_KEY_ON_SERVER_ONLY>
  datasource:
    password: <PASSWORD_ON_SERVER_ONLY>
    url: jdbc:mysql://mysql/mittagstisch?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: <USERNAME_ON_SERVER_ONLY>
  main:
    banner-mode: "off"
