#
# APPLICATION CONFIG DEV
#

spring:
  ai:
    openai:
      api-key: <OPEN_AI_API_KEY>
  datasource:
    password: <PASSWORD>
    url: jdbc:mysql://<SERVER>[:PORT]/<DATABASE>?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: <USERNAME>
  main:
    banner-mode: "off"
