name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - name: Determine next version
        id: determine_next_version
        run: |
          set -euo pipefail

          pnpm dlx semantic-release --dry-run | tee release.log

          VERSION=$(grep "next release version is" release.log \
            | sed -E 's/.* ([0-9]+\.[0-9]+\.[0-9]+).*/\1/')

          echo "Next version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "release=true" >> $GITHUB_OUTPUT

      - name: Update version files
        if: steps.determine_next_version.outputs.release == 'true'
        run: |

          # root package.json
          pnpm version $VERSION --no-git-tag-version

          # frontend package.json
          cd frontend
          pnpm version $VERSION --no-git-tag-version
          cd ..

          mvn -f backend/pom.xml versions:set \
            -DnewVersion=$VERSION \
            -DgenerateBackupPoms=false

      - name: Commit & tag release
        if: steps.determine_next_version.outputs.release == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git commit -am "chore(release): v$VERSION"
          git tag v$VERSION
          git push origin main --tags

      - name: Create GitHub release
        if: steps.determine_next_version.outputs.release == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v$VERSION
          release_name: v$VERSION
          generate_release_notes: true
